### 任务2.1掌握Numpy数组对象ndarray
### 2.1.1创建数组对象

### 1、数组属性
表2-1数组的属性及其说明

属性|说明|
-------|---------------------------------|
ndim|返回int ,表示数组的维数|
shape|返回tuple,表示数组的形状，尺寸，n行，m列的举证，形状为（n,m)|
size|返回int，表示数组的元素总数，等于数组的形状的乘积|
dtype|返回data-type,描述数组的类型|
itemize|返回int，表示数组的每个元素的大小。|


### 2、创建数组
##### Numpy提供的array 函数可以创建 一维或多维数组
numpy.array(obj,dtype=None,copy=True,order='K',subok=False,ndmin=0)
表2-2 array函数的参数说明

参数名称|说明|
----------|---------------------------|
obj|接收数组array,表示想要创建的数组，无默认值|
dtype|接收data-type ,表示数组所需要的数据类型，如果未给定 ，则选择保存对象所需要的最小类型。默认为None |
ndmin|接收int,指定数组生成数组应该具有的最小维数，默认为None

In [1]:
#创建一维数组 ------->numpy.array()
import numpy as np
arr1 = np.array([1,2,3,4])#创建一维数组
print("创建的数组为：",arr1)

创建的数组为： [1 2 3 4]


In [2]:
#创建二维数组
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]
                ])
print("创建的数组为：\n",arr2)

创建的数组为：
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
#查看数组的属性------>数组名.函数名
print("数组的维数：",arr1.ndim)
print("数组的形状：",arr1.shape)
print("数组的元素总数",arr1.size)
print("数组的数据类型：",arr1.dtype)
print("数组的每个元素的大小：",arr1.itemsize)


数组的维数： 1
数组的形状： (4,)
数组的元素总数 4
数组的数据类型： int64
数组的每个元素的大小： 8


In [4]:
print("二维数组的维数：\n",arr2.ndim)
print("二维数组的形状：\n",arr2.shape)
print("二维数组的元素总数:\n",arr2.size)
print("二维数组的数据类型：\n",arr2.dtype)
print("二维数组的每个元素的大小：\n",arr2.itemsize)

二维数组的维数：
 2
二维数组的形状：
 (3, 4)
二维数组的元素总数:
 12
二维数组的数据类型：
 int64
二维数组的每个元素的大小：
 8


In [5]:
#重新设置数组的shape属性
arr2.shape = 4,3
print("重新设置的数组shape 属性后的arr2：\n",arr2)

重新设置的数组shape 属性后的arr2：
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 以上都是先创建一个python序列，然后通过array 函数将其转化为数组。

### 3、创建数组的各类函数
表2-3 numpy 专门用来创建数组的函数

函数名|说明|
----------|---------------------------------------------------------------------|
arange|numpy.arrange(起始值，终止值[不包含],步长)|
linspace|numpy.inspace(起始值，终止值[默认包含]，元素个数)|
logspace|numpy.logspace(起始值幂指数， 终止幂指数[包含]，元素个数) 创建的是等比数列。10的起始次方-10的终止次方|
zeros|numpy.zeros( (n,m) ) 创建的数组的元素值全部为0|
ones|numpy.ones( (n,m) )创建的数组的元素值全部为1 |
eye |numpy.eye( n )类似 单位矩阵，主对角元素为1,其余元素全部为0，主对角元素个数为n |
diag | numpy.diag(  [v1，v2,v3，...,,vn] ) **v1,v2,v3,...,vn是主对角线上的元素值**，类似对角矩阵,除了主对角线上的元素，其余元素全部为0，主对角元素可以是0或者其他元素。

In [7]:
print("使用arange函数创建的数组为：\n",np.arange(0,1,0.1))
print("使用linspace函数创建的数组为：\n",np.linspace(0,1,10))
print("使用logspace函数创建的等比数列：\n",np.logspace(0,2,20))
print("使用zeros函数创建的全零数组：\n",np.zeros( (3,4) ))
print("使用ones函数创建的全1数组：\n",np.ones( (3,4) ))
print("使用eye函数创建的单位矩阵：\n",np.eye( 3 ))
print("使用diag函数创建的对角矩阵：\n",np.diag( [1,2,3,4] ))

使用arange函数创建的数组为：
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
使用linspace函数创建的数组为：
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
使用logspace函数创建的等比数列：
 [  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]
使用zeros函数创建的全零数组：
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
使用ones函数创建的全1数组：
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
使用eye函数创建的单位矩阵：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
使用diag函数创建的对角矩阵：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 4、数组的数据类型
####  numpy 中，所有的数组的数据类型是同质的，即数组中的所有元素类型都必须时一致的。*** 好处：更容易确定该数组所需的存储空间。***
表2-4 numpy的基本数据类型及其取值范围

数据类型|取值范围|
------------------------------------------------|
bool | 值为：True  或者 False|
inti | 通常为int32 或者 int64|
int8 | 整数，-128～127|
int16 | 整数，-32 768～32 767|
int32 | 整数，-2的31次方～2的32次方-1|
int64 | 整数，-2的63次方～2的63次方-1|
uint8 | 无符号整数，范围为0～255 |
uint16 |无符号整数，范围为0～65 535|
uint32 |无符号整数，范围为0～2的32次方-1|
uint64 |无符号整数，范围为0～2的64次方-1|
float16 | 半精度浮点数，16位，其中用1位表示正负号，用5位表示指数，用10位表示尾数|
float32 | 半精度浮点数，32位，其中用1位表示正负号，用8位表示指数，用32位表示尾数|
float64或者float| 双精浮点数，64位，其中用1位表示正负号，用11位表示指数，用52位表示位数|
complex64| 复数，分别用两个32位浮点数表示实部和虚部|
complex128或者complex|复数，分别用两个64位浮点数表示实部和虚部|

In [8]:
print("转换结果为：",np.bool(0)) #整型转换为布尔型
print("转换结果为：",np.bool(12)) 
print("转换结果为：",np.bool(12.12)) #浮点型转换为布尔型
print("转换结果为：",np.int8(12.12)) #浮点型转换为整型
print("转换结果为：",np.float(12)) #整型转换为浮点型
print("转换结果为：",np.float64(True))#布尔型转换为浮点型
print("装换结果为：",np.float64(False))

转换结果为： False
转换结果为： True
转换结果为： True
转换结果为： 12
转换结果为： 12.0
转换结果为： 1.0
装换结果为： 0.0


 #### 实例，存储餐饮企业信息的数据类型
 ##### 用一个能存储40个字符的字符串来记录商品的名称。用一个64位的整型來记录商品的库存数量。用一个64位的单精度浮点数来记录商品的价格。

In [11]:
#创建数据类型
df = np.dtype( [('goods_name',np.str_,40),
              ('goods_nums',np.int64),
              ('goods_price',np.float64)
              ] )
print("数据类型:",df)

数据类型: [('goods_name', '<U40'), ('goods_nums', '<i8'), ('goods_price', '<f8')]


In [13]:
#查看数据类型
print("数据类型为：",df['goods_name']) # 数组名['属性值']
print("数据类型为：",np.dtype( df['goods_name'] ))

数据类型为： <U40
数据类型为： <U40


可以直接查看或者使用numpy.dtype()函数查看

In [17]:
# 自定义数组数据值，然后查看数据类型
zdf = np.array( [ ('tomatoes',10,5.9),
                  ('potatoes',20,4.9),
                  ('cabbages',30,3.9)
                 ] ,dtype = df) #这句dtype =df是上面定义好的数据类型
print("自定义数据:",zdf)

自定义数据: [('tomatoes', 10, 5.9) ('potatoes', 20, 4.9) ('cabbages', 30, 3.9)]


### 2.1.2 生成随机数
#### numpy 提供了强大的随机生成数的功能。实际中都是伪随机数。与随机数相关的函数，都在random模块中，其中包括可以生成服从多种概率分布的随机数的函数。
表2-5 random模块的常用随机数生成函数

函数名|说明|
------------|--------------------------|
random|生成随机数|
rand|生成可以服从均匀分布的随机数,np.random.rand (n,m)|
randn|生成可以服从正态分布的随机数,np.random.randn(n,m) |
randint|生成给定上下限定范围的随机数,np.random.randint(low,high=None,size=None,dtype='1')|
seed|确定随机数生成器的种子|
permutation|返回一个序列的随机排列或者返回一个随机排列的范围|
Shuffle| 对一个序列进行随机排序|
binomial|产生 一个二项分布的随机数|
normal |产生正态(高斯)分布的随机数|
beta| 产生一个beta分布的随机数|
chisquare|产生卡方分布的随机数|
gamma|产生gamma分布的随机数|
uniform|产生在[0,1] 中均匀分布的随机数|

In [19]:
print("生成的随机数：\n",np.random.random(100))
print("生成的服从均匀分布的随机数组为：\n",np.random.rand(10,5))
print("生成的服从正态分布的随机数组为：\n",np.random.randn(10,5))
print("生成的给定上下限范围的随机数组为：\n",np.random.randint(2,10,size=[2,5]))

生成的随机数：
 [0.97356952 0.66407327 0.40360999 0.66102227 0.42857465 0.51978
 0.21433671 0.88571488 0.22014027 0.28995429 0.22634935 0.33200115
 0.97558826 0.24844852 0.82411602 0.28971944 0.16608196 0.50829291
 0.18998237 0.61393352 0.3704919  0.61296035 0.80095654 0.39451988
 0.75482195 0.38038336 0.05505576 0.87937784 0.54598023 0.69216929
 0.02234226 0.58168835 0.78236103 0.16969899 0.34948505 0.00462871
 0.51723043 0.49812488 0.28551224 0.06949865 0.13153862 0.92360854
 0.33972209 0.23332738 0.3223911  0.16519187 0.90142195 0.35077631
 0.85309974 0.9592765  0.91679902 0.99971143 0.21767081 0.11675317
 0.08257394 0.70803251 0.52855802 0.45687294 0.37371475 0.28331006
 0.39429957 0.26550458 0.28371738 0.09565373 0.40803314 0.88390235
 0.01527438 0.05329532 0.83847332 0.79183887 0.35835832 0.68088931
 0.21112164 0.34830947 0.73127089 0.27291189 0.97482926 0.27923442
 0.74759055 0.85284281 0.81162584 0.59576101 0.7184023  0.0204456
 0.13680865 0.13127686 0.58789298 0.65877674 0.56940349 0